### PR TITLE
Mark licenses and change to GPL-3.0-or-later

### PR DESCRIPTION
**Pull request by nfitzen**
NOTE: this requires approval from the copyright holders.
I am merely making it easier via a PR.

Requires @gamescomputersplay and @nopeless to consent to this license change.

I asked for licensing under [`GPL-3.0-or-later`] in #1, but it ended up being [`GPL-3.0-only`].
It's generally [recommended to use "or any later version"](https://www.gnu.org/licenses/gpl-faq.html#VersionThreeOrLater).

I also felt like the gitignore, requirements.txt, and README should be licensed under [CC0 1.0].

Is this okay?

[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"
[`GPL-3.0-only`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 only"
[CC0 1.0]: https://creativecommons.org/publicdomain/zero/1.0/ "Creative Commons Zero 1.0 Universal"

### CODE REVIEW

**Comment by nopeless** [comment]
I think this pr is what we need in order to not get in trouble with whichever company that made this game
I approve

**Comment by nopeless** [comment]
actually add the fair use disclaimer somewhere

**Comment by nfitzen** [comment]
@nopeless to my knowledge, game rules in general aren't copyrightable. See [17 U.S.C. &sect; 102(b)]. Also, the licensing is for the code, not the Monopoly game or trademark. You'd agree to license the code portions (contributions) you wrote under the terms I laid out in the PR branch.

I don't think there's much of a trademark issue if at all, tbh.

Quick disclaimer though: I'm not a lawyer, nor is any of this legal advice.

[17 U.S.C. &sect; 102(b)]: https://www.law.cornell.edu/uscode/text/17/102#b

**Comment by nopeless** [comment]
well if you look at the code it pretty much uses the exact cards and rules so I have my doubts. Nevertheless the pr covers the code and contributions itself as well

**Comment by nfitzen** [comment]
@nopeless actually, you're right. The cards and labels might be copyrightable. Either way, fair use doesn't require a disclaimer, though a GPL &sect; 7 exception might need to be made should the program be rendered nonfree via copyright law.

**Comment by nopeless** [comment]
i was deceived by youtube descriptions

**Comment by gamescomputersplay** [comment]
hey guys. 
I dont want to be a bottleneck for pull requests approval. Anyone wants to be a mod (or whatever it is called) for this repository?

**Comment by gamescomputersplay** [comment]
Speaking of potential copyright problems. Do you think if we rename Properties to "Blue1", "Blue2" and so on and cards to "Pay100", "Receive200" or whatever - will it solve the problem? I mean the of thepoint of the program is just to test some theories, not to "provide fun through references to business realia", so I see no problem making it as generic as possible.

**Comment by nopeless** [comment]
> hey guys.
> I dont want to be a bottleneck for pull requests approval. Anyone wants to be a mod (or whatever it is called) for this repository?

@gamescomputersplay I'm ok with being contributor

**Comment by nopeless** [comment]
> Speaking of potential copyright problems. Do you think if we rename Properties to "Blue1", "Blue2" and so on and cards to "Pay100", "Receive200" or whatever - will it solve the problem? I mean the of thepoint of the program is just to test some theories, not to "provide fun through references to business realia", so I see no problem making it as generic as possible.

@nfitzen not worth it imo

**Comment by gamescomputersplay** [comment]
alright then. 
Sent a collaborator invite - let me know if you have access now or if I need to click some other buttons. (Sorry, I don't know my way around GitHub well yet).

**Comment by nfitzen** [comment]
@gamescomputersplay tbh, this was [probably] the last PR I was gonna send, to get the basic legal stuff sorted on your end. Regardless of whether I had access to modify the repository, this PR still would've required your permission.

**Pull request merged**
